package com.vetsoft.ccms.controller;

import java.util.Set;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.vetsoft.ccms.MainBootApp;
import com.vetsoft.ccms.controller.utils.ManuvalCommands;
import com.vetsoft.ccms.controller.utils.Utiles;
import com.vetsoft.ccms.dal.UserDAL;
import com.vetsoft.ccms.dal.UserRepository;
import com.vetsoft.ccms.netty.parser.BaseUtil;
import com.vetsoft.ccms.netty.server.ChannelDetails;
import com.vetsoft.ccms.netty.server.ServerHandler;

@RestController
@RequestMapping(value = "/push")
public class UIConfController {

	private final Logger LOG = LoggerFactory.getLogger(getClass());

	private final UserRepository userRepository;

	private final UserDAL userDAL;

	@Autowired
	ServerHandler serverHandler;
	
	public UIConfController(UserRepository userRepository, UserDAL userDAL) {
		this.userRepository = userRepository;
		this.userDAL = userDAL;
		System.out.println("++++++++++++++++++++ UIConfController INTIALLIZED ===========================");
	}

	
	/*
	 * This function will send dcu  conf change request to device 
	 * this will be invoked from the UI, 
	 * node_data : is the dcu configuration data need to sync with device
	 * file_identifier : file id of the node conf generated by UI
	 * 
	 * this info will be stored in DB and retried by the scheduler in case of failure.
	 */
	@RequestMapping(value = "/sys_conf", method = RequestMethod.GET)
	public String syncSysConf(@RequestParam("dcu_id") String dcu_id, 
			@RequestParam("buffer") String buffer,
			@RequestParam("dcu_identifier") String dcu_identifier, 
			@RequestParam("node_data") String node_data, 
			@RequestParam("file_idetifier") String file_idetifier
			) {
		
		LOG.info("SYS CONF SYNC REQUEST FROM UI : "+ dcu_id + " "+ buffer);
		try{
			
			String CRC = Integer.toHexString(BaseUtil.calculateCRC(BaseUtil.convertHexToString(buffer.toString()).toCharArray(), BaseUtil.convertHexToString(buffer.toString()).length()));
			String chnage_request_packet = buffer+CRC;
			
		//	serverHandler.sendMessageToClient(buffer+CRC, dcu_id, 1);
			
			serverHandler.sendDcuConfSyncMesageToClient(chnage_request_packet, dcu_id, file_idetifier, node_data, dcu_identifier);
		}catch(Exception e){
			LOG.error("Exception while processing sysnc sys conf for device : "+ dcu_id);
		}
		LOG.info("SYS SYNC DONE SUCCESSFULLY");
		return "OK";
	}
	
	
	
	
	/*
	 * This function will send node conf change request to device 
	 * this will be invoked from the UI, 
	 * node_data : is the node configuration data need to sync with device
	 * file_identifier : file id of the node conf generated by UI
	 * 
	 * this info will be stored in DB and retried by the scheduler in case of failure.
	 */
	@RequestMapping(value = "/sync_node_conf", method = RequestMethod.GET)
	public String syncNodeConfFromUI(@RequestParam("dcu_id") String dcu_id, 
			@RequestParam("dcu_identifier") String dcu_identifier, 
			@RequestParam("node_data") String node_data, 
			@RequestParam("file_idetifier") String file_idetifier) {
		
		String buffer = Utiles.getNodeConfInformationExchangePacket(file_idetifier, dcu_identifier);
		LOG.info("NODE CONF SYNC REQUEST FROM UI : "+ dcu_id + " "+ buffer);
		try{
			String CRC = Integer.toHexString(BaseUtil.calculateCRC(BaseUtil.convertHexToString(buffer.toString()).toCharArray(), BaseUtil.convertHexToString(buffer.toString()).length()));
			
			serverHandler.sendNodeConfigurationChangeRequestToClient(buffer+CRC, dcu_id, file_idetifier, node_data, dcu_identifier);
		}catch(Exception e){
			LOG.error("Exception while processing sysnc sys conf for device : "+ dcu_id);
		}
		LOG.info("NODE CONF SYNC DONE SUCCESSFULLY");
		return "OK";
	}
	
	
	/*
	 * This function will send Scheduler conf change request to device 
	 * this will be invoked from the UI, 
	 * node_data : is the Scheduler configuration data need to sync with device
	 * file_identifier : file id of the node conf generated by UI
	 * 
	 * this info will be stored in DB and retried by the scheduler in case of failure.
	 */
	@RequestMapping(value = "/sync_scheduler_conf", method = RequestMethod.GET)
	public String syncSchedulerConfFromUI(@RequestParam("dcu_id") String dcu_id, 
			@RequestParam("dcu_identifier") String dcu_identifier, 
			@RequestParam("node_data") String node_data, 
			@RequestParam("file_idetifier") String file_idetifier) {
		
		String buffer = Utiles.getScheduleConfInformationExchangePacket(file_idetifier, dcu_identifier);
		LOG.info("SCHEDULER CONF SYNC REQUEST FROM UI : "+ dcu_id + " "+ buffer);
		try{
			String CRC = Integer.toHexString(BaseUtil.calculateCRC(BaseUtil.convertHexToString(buffer.toString()).toCharArray(), BaseUtil.convertHexToString(buffer.toString()).length()));
			
			serverHandler.sendSchedulerConfigurationChangeRequestToClient(buffer+CRC, dcu_id, file_idetifier, node_data, dcu_identifier);
		}catch(Exception e){
			LOG.error("Exception while processing sysnc sys conf for device : "+ dcu_id);
		}
		LOG.info("SCHEDULER CONF SYNC DONE SUCCESSFULLY");
		return "OK";
	}
	
	
	
	@RequestMapping(value = "/manuval_on", method = RequestMethod.GET)
	public String manuvalOn(@RequestParam("dcu_serial_number") String dcu_serial_number,
			@RequestParam("dcu_identifier") int dcu_identifier
			) {
		LOG.debug("MANUVAL ON COMMAND : "+ dcu_serial_number + " ID : "+ dcu_identifier);
		String buffer = ManuvalCommands.turnOnLight(BaseUtil.getHexString(dcu_serial_number), dcu_identifier);
		
		serverHandler.sendManuvalOnOffRequest(buffer, dcu_serial_number);
		return "DONE";
	}
	
	@RequestMapping(value = "/manuval_off", method = RequestMethod.GET)
	public String manuvalOff(@RequestParam("dcu_serial_number") String dcu_serial_number,
			@RequestParam("dcu_identifier") int dcu_identifier
			) {
		LOG.debug("MANUVAL OFF COMMAND : "+ dcu_serial_number + " ID : "+ dcu_identifier);
		String buffer = ManuvalCommands.turnOffLight(BaseUtil.getHexString(dcu_serial_number), dcu_identifier);
		
		serverHandler.sendManuvalOnOffRequest(buffer, dcu_serial_number);
		return "DONE";
	}
	@RequestMapping(value = "/hafe_open_connections", method = RequestMethod.GET)
	public String clearHafeOpenedConnections(){
		
		Set<String> keys = MainBootApp.hafe_opened_channels_list.keySet();
		
		for(String key : keys){
			ChannelDetails ctx = MainBootApp.hafe_opened_channels_list.get(key);
			try {
				LOG.error("CLOSE HAFE OPENED CONNECTION : " + key  + " IP : "+ ctx.ip);
				serverHandler.closeHafeOpenedConnections(ctx.ctx);
				MainBootApp.hafe_opened_channels_list.remove(key);
			} catch (Exception e) {
				LOG.error("ERROR WHILE SENDING HAFE OPENED CONNECTION CLOSE EVENT : "+e.getMessage() + " IP : "+ ctx.ip);
			}
		}
		return "DONE";
	}
	/*@RequestMapping(value = "/schedule_conf", method = RequestMethod.GET)
	public String syncScheduleConf(@RequestParam("dcu_id") String dcu_id) {
		
		String buffer = getScheduleConfInformationExchangePacket();
		LOG.info("SCHEDULE CONF SYNC REQUEST FROM UI : "+ dcu_id + " "+ buffer);
		try{
			
			String CRC = Integer.toHexString(BaseUtil.calculateCRC(BaseUtil.convertHexToString(buffer.toString()).toCharArray(), BaseUtil.convertHexToString(buffer.toString()).length()));
			
			serverHandler.sendMessageToClient(buffer+CRC, dcu_id, 4);
			
		}catch(Exception e){
			LOG.error("Exception while processing sysnc sys conf for device : "+ dcu_id);
		}
		LOG.info("NODE CONF SYNC DONE SUCCESSFULLY");
		return "OK";
	}
	*/


	
	

	
private String getScheduleConfInformationExchangePacket() {

	
	StringBuffer sb = new StringBuffer();
	
long UTC_date = (System.currentTimeMillis()/1000);
	
	System.out.println(Long.toHexString(UTC_date));
	
	try {
		sb.append("55AA55AA")
		.append("01")
		.append("00")
		.append("000007FB")
		.append("3E")
		.append("02")
		.append("0006") // pay load len
		.append("01")
		.append("04")
		.append(Long.toHexString(UTC_date))
		
		;
	} catch (Exception e) {
		System.out.println("Exception while making init command :"+ e.getMessage());
	}
	return sb.toString();

	}

/*

private String getNodeConfInformationExchangePacket() {
		
		StringBuffer sb = new StringBuffer();
		
long UTC_date = (System.currentTimeMillis()/1000);
		
		System.out.println(Long.toHexString(UTC_date));
		
		try {
			sb.append("55AA55AA")
			.append("01")
			.append("00")
			.append("000007FB")
			.append("3E")
			.append("02")
			.append("0006") // pay load len
			.append("01")
			.append("03")
			.append(Long.toHexString(UTC_date))
			
			;
		} catch (Exception e) {
			System.out.println("Exception while making init command :"+ e.getMessage());
		}
		return sb.toString();
	}


	private String getInformationExchangePacket(String dcu_id) {
		
		StringBuffer sb = new StringBuffer();
		
		try {
			sb.append("55AA55AA")
			.append("01")
			.append("00")
			.append("000007FB")
			.append("3E")
			.append("02")
			.append("001F")
			.append("06")
			.append("03")
			.append("57E4D904")
			
			.append("01")
			.append("57E4D512")
			
			
			.append("0E")
			.append("57E4D512")
			
			
			.append("04")
			.append("57E4D907")
			
			
			.append("16")
			.append("57E4D24F")
			.append("17")
			.append("57E3B568")
			.append("9F")
			;
		} catch (Exception e) {
			System.out.println("Exception while making init command :"+ e.getMessage());
		}
		return sb.toString();
	}*/


	/*@RequestMapping(value = "/node_conf", method = RequestMethod.GET)
	public String syncNodeConf(@RequestParam("dcu_id") String dcu_id) {
		
		String buffer = getNodeConfInformationExchangePacket();
		LOG.info("NODE CONF SYNC REQUEST FROM UI : "+ dcu_id + " "+ buffer);
		try{
			String CRC = Integer.toHexString(BaseUtil.calculateCRC(BaseUtil.convertHexToString(buffer.toString()).toCharArray(), BaseUtil.convertHexToString(buffer.toString()).length()));
			
			serverHandler.sendMessageToClient(buffer+CRC, dcu_id, 3);
			
		}catch(Exception e){
			LOG.error("Exception while processing sysnc sys conf for device : "+ dcu_id);
		}
		LOG.info("NODE CONF SYNC DONE SUCCESSFULLY");
		return "OK";
	}*/
	
}