# Local MongoDB config
spring.data.mongodb.database=${mongodb.database:ccms}
spring.data.mongodb.port=${mongodb.port:27017}
spring.data.mongodb.host=${mongodb.host:localhost}

# app config
server.port=${server.port:8102}
spring.application.name=BootMongo
server.context-path=${server.context-path:/user}
