#This file is Used by our application
log4j.rootLogger=INFO, toLogFile

# Create  appender 'toFile' to send log to 'Server.log' file
log4j.appender.toLogFile=org.apache.log4j.RollingFileAppender
log4j.appender.toLogFile.File=/home/CCMS/roadmap/logs/ccms.log
log4j.appender.toLogFile.MaxFileSize=200MB
log4j.appender.toLogFile.MaxBackupIndex=20
log4j.appender.toLogFile.layout=org.apache.log4j.PatternLayout
log4j.appender.toLogFile.layout.ConversionPattern= %d [%F:%L][%p]:%m%n

log4j.logger.org.mongodb.driver=OFF

